export enum ErrorCodes {
	INVALID_PHONENUMBER = 'INVALID_PHONENUMBER',
	ALREADY_SIGNED_UP = 'ALREADY_SIGNED_UP',
	WAIT_BEFORE_SIGN_UP = 'WAIT_BEFORE_SIGN_UP',
	SIGN_UP_NOT_FOUND = 'SIGN_UP_NOT_FOUND',
};